### PR TITLE
Update html file

### PR DESCRIPTION
**Pull request by BethanyJ123**
I think it is ready now

### CODE REVIEW

**Comment by Ann-Beck** [comment]
@bill-isobvious you need to add a bit more about what we do with the trash.

**Comment by BethanyJ123** [comment]
@adam-isobvious OK I will update it.

**Comment by BethanyJ123** [comment]
@adam-isobvious OK I have added a bit more content.  Is that good now?

**Comment by Ann-Beck** [comment]
@bill-isobvious That content looks good.  But can you add a bit of formatting?

**Comment by BethanyJ123** [comment]
@adam-isobvious OK does this work now?

**Comment by Ann-Beck** [comment]
@bill-isobvious OK that looks great!  Thanks for the work.  I'll merge it now.

**Pull request merged**
